### ISSUE TITLE
Error with LazyVim (diff than just Lazy.nvim)

### ISSUE THREAD

**Issue by r3k2** [jackMort/ChatGPT.nvim#261]
Hello I have on my lua/plugins/chatgpt.lua

```
return {
  "jackMort/ChatGPT.nvim",
  event = "VeryLazy",
  config = function()
    require("chatgpt").setup({
      api_key_cmd = "gopass show -o -f chatgpt/apikey",
    })
  end,
  dependencies = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope.nvim",
  },
  keys = {
    { "<leader>Cc", "<cmd>ChatGPT<cr>", desc = "ChatGPT" },
  },
}
```
but when I do :ChatGPTRun
errors out with:
```
Error executing Lua callback: ...vim/lazy/ChatGPT.nvim/lua/chatgpt/flows/actions/init.lua:59: attempt to index local 'item' (a nil value)
stack traceback:
	...vim/lazy/ChatGPT.nvim/lua/chatgpt/flows/actions/init.lua:59: in function 'run_action'
	...rek2/.local/share/nvim/lazy/ChatGPT.nvim/lua/chatgpt.lua:46: in function 'run_action'
	...2/.local/share/nvim/lazy/ChatGPT.nvim/plugin/chatgpt.lua:14: in function <...2/.local/share/nvim/lazy/ChatGPT.nvim/plugin/chatgpt.lua:13>
```

**Comment by wakatara** [comment]
@r3k2 

What did you do to fix this? 

I have *precisely* the same error in my neovim, so quite curious as to what you did to fix this (and only with ChatGPT Run) since I assume you puzzled it out since you both opened and closed the ticket... =] 

I'm assuming it is something with one of my setup configs but unsure where my config might have gone wrong or be conflicting here. 

thanks!

**Comment by desirelabs** [comment]
Hello, for those who are passing here, the command `ChatGPTRun` is expecting a command to run after. 
Just space tab to see the available ones.
